
name: 'portfolio_ae'
version: '1.0.0'

profile: 'portfolio_ae'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  portfolio_ae:
    staging:
      +schema: bronze
      +materialized: view
    intermediate:
      +schema: silver
      +materialized: table
    marts:
      +schema: gold
      +materialized: table
