with source as (
    select * from {{ source('raw_cache', 'nota_fiscal') }}
),

renamed as (
    select
        cast(ID as string) as ID,
        cast(codCliente as int64) as codCliente,
        cast(codEmpresa as int64) as codEmpresa,
        cast(codEstatisticaFaturamento as string) as codEstatisticaFaturamento,
        cast(codEstatisticaVendas as string) as codEstatisticaVendas,
        cast(codNota as int64) as codNota,
        safe_cast(safe_cast(codRepresentante as float64) as int64) as codRepresentante,
        cast(codSituacao as string) as codSituacao,
        cast(codSituacaoDuplicata as string) as codSituacaoDuplicata,
        cast(codTipoFaturamento as string) as codTipoFaturamento,
        cast(condVenda as string) as condVenda,
        cast(dataEmissao as date) as dataEmissao,
        cast(dataEntrega as string) as dataEntrega,
        cast(dataHoraGeracao as datetime) as dataHoraGeracao,
        cast(estatisticaFaturamento as string) as estatisticaFaturamento,
        cast(estatisticaVendas as string) as estatisticaVendas,
        cast(estruturaComercial as string) as estruturaComercial,
        cast(idCliente as string) as idCliente,
        cast(idEmpresa as string) as idEmpresa,
        cast(idNotaFiscal as string) as idNotaFiscal,
        cast(idRepresentante as string) as idRepresentante,
        cast(localEntrega as string) as localEntrega,
        cast(natOperacaoCapa as string) as natOperacaoCapa,
        {{ mask_pii_info('nomeCliente','name') }} as nomeCliente,
        {{ mask_pii_info('nomeRepresentante','name') }} as nomeRepresentante,
        cast(pesoBruto as float64) as pesoBruto,
        cast(pesoLiquido as float64) as pesoLiquido,
        cast(qtdVolumes as int64) as qtdVolumes,
        {{ mask_pii_info('razaoEmpresa','name') }} as razaoEmpresa,
        cast(serieFiscal as int64) as serieFiscal,
        cast(situacao as string) as situacao,
        cast(situacaoDuplicata as string) as situacaoDuplicata,
        cast(tabelaPreco as string) as tabelaPreco,
        cast(tipoFaturamento as string) as tipoFaturamento,
        cast(tipoNota as string) as tipoNota,
        {{ convert_money('valorBaseCOFINS') }} as valorBaseCOFINS,
        {{ convert_money('valorBaseICMS') }} as valorBaseICMS,
        {{ convert_money('valorBaseICMSST') }} as valorBaseICMSST,
        {{ convert_money('valorBaseIPI') }} as valorBaseIPI,
        {{ convert_money('valorBasePIS') }} as valorBasePIS,
        {{ convert_money('valorCOFINS') }} as valorCOFINS,
        {{ convert_money('valorDesconto') }} as valorDesconto,
        {{ convert_money('valorICMS') }} as valorICMS,
        {{ convert_money('valorICMSST') }} as valorICMSST,
        {{ convert_money('valorIPI') }} as valorIPI,
        {{ convert_money('valorLiquido') }} as valorLiquido,
        {{ convert_money('valorNF') }} as valorNF,
        {{ convert_money('valorPIS') }} as valorPIS,
        cast(vlrDIFALDestinatario as string) as vlrDIFALDestinatario,
        cast(vlrDIFALRemetente as string) as vlrDIFALRemetente,
        cast(vlrFCPDIFAL as string) as vlrFCPDIFAL,
        cast(vlrFCPICMS as string) as vlrFCPICMS,
        cast(vlrFCPST as string) as vlrFCPST,
        cast(vlrFaturadoBruto as string) as vlrFaturadoBruto,
        cast(vlrFrete as string) as vlrFrete,
        cast(vlrLiquido as string) as vlrLiquido,
        cast(vlrOutrasDespesas as string) as vlrOutrasDespesas,
        cast(vlrSeguro as string) as vlrSeguro,
        cast(extracted_at as datetime) as extracted_at,
        {{ generate_audit_columns() }}

    from source
)

select * from renamed