with source as (
    select * from {{ source('raw_cache', 'contas_receber') }}
),

renamed as (
    select
        cast(ID as string) as ID,
        {{ mask_pii_info('agenciaBancaria') }} as agenciaBancaria,
        {{ mask_pii_info('atendente') }} as atendente,
        cast(baseComissAtenFat as float64) as baseComissAtenFat,
        cast(baseComissAtenLiq as float64) as baseComissAtenLiq,
        cast(baseComissFat as float64) as baseComissFat,
        cast(baseComissLiq as float64) as baseComissLiq,
        cast(codCliente as int64) as codCliente,
        cast(codDuplicata as string) as codDuplicata,
        cast(codEmpresa as int64) as codEmpresa,
        cast(codRepresentante as int64) as codRepresentante,
        cast(comissAtenFat as float64) as comissAtenFat,
        cast(comissAtenLiq as float64) as comissAtenLiq,
        cast(comissFat as float64) as comissFat,
        cast(comissLiq as float64) as comissLiq,
        cast(condicaoVenda as string) as condicaoVenda,
        cast(dataBxContabil as date) as dataBxContabil,
        cast(dataEmissao as date) as dataEmissao,
        cast(dataFluxoCaixa as string) as dataFluxoCaixa,
        cast(dataHoraGeracao as datetime) as dataHoraGeracao,
        cast(dataPagamento as date) as dataPagamento,
        cast(dataVencOriginal as date) as dataVencOriginal,
        cast(dataVencimento as date) as dataVencimento,
        cast(descPrazoConcedido as string) as descPrazoConcedido,
        cast(descPrazoRealizado as string) as descPrazoRealizado,
        cast(diasDescDupl as string) as diasDescDupl,
        cast(idCliente as string) as idCliente,
        cast(idDuplicata as string) as idDuplicata,
        cast(idEmpresa as string) as idEmpresa,
        cast(idRepresentante as string) as idRepresentante,
        cast(listada as string) as listada,
        cast(moeda as string) as moeda,
        {{ mask_pii_info('nomeCliente','name') }} as nomeCliente,
        {{ mask_pii_info('nomeRepresentante','name') }} as nomeRepresentante,
        cast(numBancario as string) as numBancario,
        cast(percComissao as float64) as percComissao,
        cast(percComissaoAten as float64) as percComissaoAten,
        cast(percDesconto as float64) as percDesconto,
        cast(portador as string) as portador,
        cast(prazoConcedido as int64) as prazoConcedido,
        cast(prazoRealizado as int64) as prazoRealizado,
        cast(priNotaFiscal as int64) as priNotaFiscal,
        cast(qtdIndexador as float64) as qtdIndexador,
        cast(qtdeNotaFiscal as int64) as qtdeNotaFiscal,
        {{ mask_pii_info('razaoEmpresa','name') }} as razaoEmpresa,
        cast(situacao as string) as situacao,
        cast(tipoBaixa as string) as tipoBaixa,
        cast(tipoDesconto as string) as tipoDesconto,
        cast(tipoDocumento as string) as tipoDocumento,
        cast(tipodeCobranca as string) as tipodeCobranca,
        {{ convert_money('vlrComLiqAte') }} as vlrComLiqAte,
        {{ convert_money('vlrComLiqRep') }} as vlrComLiqRep,
        {{ convert_money('vlrComisLiqAte') }} as vlrComisLiqAte,
        {{ convert_money('vlrComisLiqRep') }} as vlrComisLiqRep,
        {{ convert_money('vlrContratual') }} as vlrContratual,
        {{ convert_money('vlrCorrMonet') }} as vlrCorrMonet,
        {{ convert_money('vlrDesconto') }} as vlrDesconto,
        {{ convert_money('vlrJuros') }} as vlrJuros,
        {{ convert_money('vlrMultaAtraso') }} as vlrMultaAtraso,
        {{ convert_money('vlrMultaPaga') }} as vvlrMultaPaga,
        {{ convert_money('vlrOriginal') }} as vlrOriginal,
        {{ convert_money('vlrRetCOFINS') }} as vlrRetCOFINS,
        {{ convert_money('vlrRetCSSL') }} as vlrRetCSSL,
        {{ convert_money('vlrRetIR') }} as vlrRetIR,
        {{ convert_money('vlrRetPIS') }} as vlrRetPIS,
        {{ convert_money('vlrTitulo') }} as vlrTitulo,
        {{ convert_money('vlrTotalNF') }} as vlrTotalNF,        
        cast(extracted_at as datetime) as extracted_at,
        {{ generate_audit_columns() }}

    from source
)

select * from renamed
